### ISSUE TITLE
Pretty printers are not working anymore

### ISSUE THREAD

**Issue by TotoGaz** [GEOS-DEV/GEOS#2639]
The [`LvArray` pretty printers](https://github.com/GEOS-DEV/LvArray/blob/develop/scripts/gdb-printers.py) are providing a convenient `gdb_view` to the `LvArray` data. The error message being:
```
Traceback (most recent call last):
  File "/tmp/tmp.EtfQgEUXLg/src/coreComponents/LvArray/scripts/gdb-printers.py", line 57, in children
    return [('gdb_view', arr)] + LvArrayPrinter.children(self)
  File "/tmp/tmp.EtfQgEUXLg/src/coreComponents/LvArray/scripts/gdb-printers.py", line 27, in children
    + [(f.name, self.val[f.name]) for f in self.real_type().fields() if not f.is_base_class]
  File "/tmp/tmp.EtfQgEUXLg/src/coreComponents/LvArray/scripts/gdb-printers.py", line 27, in <listcomp>
    + [(f.name, self.val[f.name]) for f in self.real_type().fields() if not f.is_base_class]
gdb.error: Missing ELF symbol "LvArray::ChaiBuffer<int>::hasShallowCopy".
```
Quite recently, they stop working on my box, which I did not modify.

**Steps to reproduce**
Try to print any `LvArray` instance in `gdb`.

**Platform:**
- Machine: my workstation (which used to be OK)
- Compiler: I use g++ 9.4 from ubuntu 20.04
- GEOS version: quite recent.

**Additional context**
The exact same setup was working for me. It has stopped working a couple of weeks ago, maybe 2 months? Max 3.

**Comment by TotoGaz** [comment]
It's now working again. I think that I must have had some deployment/installation/compilation issue...
